#pertemuan 10
Naive Bayes

#Library

In [151]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

# Load Data

In [152]:
df = pd.read_csv("https://raw.githubusercontent.com/rahmantaufik27/dataset/main/study/weather_nb_dataset.csv")
df

     Outlook  Temp Humidity Windy Play
0      Rainy   Hot     High     f   no
1      Rainy   Hot     High     t   no
2   Overcast   Hot     High     f  yes
3      Sunny  Mild     High     f  yes
4      Sunny  Cool   Normal     f  yes
5      Sunny  Cool   Normal     t   no
6   Overcast  Cool   Normal     t  yes
7      Rainy  Mild     High     f   no
8      Rainy  Cool   Normal     f  yes
9      Sunny  Mild   Normal     f  yes
10     Rainy  Mild   Normal     t  yes
11  Overcast  Mild     High     t  yes
12  Overcast   Hot   Normal     f  yes
13     Sunny  Mild     High     t   no

# Preprocessing

In [153]:
# pisahkan data target
X_train = df.drop('Play',axis='columns')
y_train = df['Play']

* kita ubah nilai outlook.temp,humidity,windy ke integer
* hal ini ditujukan untuk menyelesaikan nilai inputan modeling naive bayes yang ada di librar python

In [154]:
# buat dataframe baru dengan encoding data
numerics = LabelEncoder()
X_train['outlook_n'] = numerics.fit_transform(X_train['Outlook'])
X_train['temp_n'] = numerics.fit_transform(X_train['Temp'])
X_train['humidity_n'] = numerics.fit_transform(X_train['Humidity'])
X_train['windy_n'] = numerics.fit_transform(X_train['Windy'])
X_train = X_train.drop(['Outlook','Temp','Humidity','Windy'],axis='columns')
X_train

    outlook_n  temp_n  humidity_n  windy_n
0           1       1           0        0
1           1       1           0        1
2           0       1           0        0
3           2       2           0        0
4           2       0           1        0
5           2       0           1        1
6           0       0           1        1
7           1       2           0        0
8           1       0           1        0
9           2       2           1        0
10          1       2           1        1
11          0       2           0        1
12          0       1           1        0
13          2       2           0        1

# Modeling

In [155]:
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

# Evaluation

In [156]:
nb.score(X_train, y_train)

0.8571428571428571

# Tugas
Buat prediksi apakah hari ini bermain golf atau tidak jika diketahui kondisi hari ini adalah Outlook = Sunny,Temperature= Hot,Humidity= Normal, dan Windy=False

In [157]:
df = pd.read_csv("https://raw.githubusercontent.com/rahmantaufik27/dataset/main/study/weather_nb_dataset.csv")
df

     Outlook  Temp Humidity Windy Play
0      Rainy   Hot     High     f   no
1      Rainy   Hot     High     t   no
2   Overcast   Hot     High     f  yes
3      Sunny  Mild     High     f  yes
4      Sunny  Cool   Normal     f  yes
5      Sunny  Cool   Normal     t   no
6   Overcast  Cool   Normal     t  yes
7      Rainy  Mild     High     f   no
8      Rainy  Cool   Normal     f  yes
9      Sunny  Mild   Normal     f  yes
10     Rainy  Mild   Normal     t  yes
11  Overcast  Mild     High     t  yes
12  Overcast   Hot   Normal     f  yes
13     Sunny  Mild     High     t   no

In [158]:
# pisahkan data target
X_train = df.drop('Play', axis='columns')
y_train = df['Play']

In [159]:
# Encoding kondisi cuaca hari ini
outlook_today = 2
temp_today = 1
humidity_today = 1
windy_today = 0
prediction = nb.predict([[outlook_today, temp_today, humidity_today, windy_today]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [160]:
# Menampilkan hasil prediksi
print(f"Probabilitas tidak bermain golf / bermain golf: {nb.predict_proba ([[outlook_today, temp_today, humidity_today, windy_today]])}")
if prediction == 0:
    print("Hari ini tidak bermain golf.")
else:
    print("Hari ini bermain golf.")

Probabilitas tidak bermain golf / bermain golf: [[0.12487422 0.87512578]]
Hari ini bermain golf.

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
<ipython-input-160-c351c2a03154>:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if prediction == 0: